/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f303xc.h"
#include "Room.h"   // <-- This should contain your initialise_board() prototype
#include "I2C.h"

int main(void)
{
    // Initialise everything: GPIO, ADC, timers, LCD, magnetometer, servos
    initialise_board();
    I2CInitialise();
    // Main loop does nothing — all logic is interrupt-driven
    while (1)
    {
        __WFI();   // Wait For Interrupt (low power, safe)
    }
}
